export const GET_BOOKMARKS = "GET_BOOKMARKS";
export const CREATE_BOOKMARK = "CREATE_BOOKMARK";
export const UPDATE_BOOKMARK = "UPDATE_BOOKMARK";
export const DELETE_BOOKMARK = "DELETE_BOOKMARK";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

export const AUTH = "AUTH";
export const SESSION = "SESSION";
export const LOGOUT = "LOGOUT";
